# Module 6 Activity

During this module we are learning about computational statistics which is a branch of mathematical sciences concerned with efficient methods for obtaining numerical solutions to statistically formulated problems.

In this activity you are going to go through the process of calculating Expectation Maximization as shown in the lecture notes and slides using the following two column example. 

In [2]:
import numpy as np

# Define the columns
column_1 = np.array([1, 4, 1, 4])
column_2 = np.array([2, 2, 3, 3])

# Create the 2-column array
x = np.column_stack((column_1, column_2))
print(x)

[[1 2]
 [4 2]
 [1 3]
 [4 3]]


In [29]:
# Column means
column_mean = np.asarray([np.mean(x_col) for x_col in x.T])
# Column standard deviations
column_std = np.asarray([np.std(x_col) for x_col in x.T])

In [39]:
column_mean.reshape(2,1)

array([[2.5],
       [2.5]])

In [38]:
column_std.reshape(2,1)

array([[1.5],
       [0.5]])

In [44]:
# Mu
mu = column_mean * np.array([1, 1]) + column_std * np.random.randn(2,1)
mu

array([[2.30264539, 2.43421513],
       [3.6875464 , 2.8958488 ]])

In [47]:
#Sigma
sigma = np.mean(column_mean) * np.array([1,1])
sigma

array([2.5, 2.5])

In [50]:
#P_k
K = 2
P_k = np.array([1, 1]) / K

In [4]:
# Create E Step
def estep(p, x, mean, std):
    for pi in p:
          gamma = np.zeros((N, K))


In [5]:
# Create M-Step

Please add your Jupyter Notebook in HTML format to the discussion board found under Module 6. You are encouraged to review other students' submissions to check and discuss differences in your approaches. 